language: cpp

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install llvm-9
  - pip install conan cmake

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-9
            - clang++-9



before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DENABLE_COVERAGE=ON -DENABLE_FUZZING=ON -DENABLE_TESTING=ON -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_LEAK=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON .
  - cmake --build . -- -j4
  - ctest -j4

after_script:
  - allgcnoFiles=$(find . -name "*.gcno")
  - llvm-cov-9 gcov $allgcnoFiles
  - bash <(curl -s https://codecov.io/bash)