language: cpp

before_install:
  - sudo apt update

install:
  - sudo apt install clang llvm-9 python3-dev python3-pip python-pip build-essential libssl-dev
  - sudo pip install conan
  - sudo pip install --user --upgrade pip
  - conan config set general.revisions_enabled=1
  - python --version
  - python3 --version
  - pip --version
  - pip3 --version
  
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

jobs:
  - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
          packages:
          - g++-9
          - cmake
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"



before_script:
  - eval "${MATRIX_EVAL}"
  - "export DISPLAY=:99.0"

script:
  - mkdir build && cd build
  - cmake -DENABLE_COVERAGE=ON -DENABLE_FUZZING=ON -DENABLE_TESTING=ON ..
  - cmake --build . -- -j4
  - ctest --output-on-failure -j4

after_script:
  - allgcnoFiles=$(find . -name "*.gcno")
  - llvm-cov-9 gcov $allgcnoFiles
  - bash <(curl -s https://codecov.io/bash)
