#ifndef BATTLECITY_ENUMS_HPP
#define BATTLECITY_ENUMS_HPP

#include "include/enum.h"

BETTER_ENUM(ESpriteId, int, UNKNOWN, MAIN_TANK1, MAIN_TANK2)

BETTER_ENUM(ETexture, int, UNKNOWN, MAIN_SHEET)

BETTER_ENUM(EFont, int, SANSATION)

BETTER_ENUM(EInputOption, int, TEST)

#endif// BATTLECITY_ENUMS_HPP