option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" OFF)

if(ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy-10)
    if(CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} -checks=-*,clang-analyzer-*,-clang-analyzer-cplusplus*,-header-filter=${CMAKE_SOURCE_DIR}/*)
        message(===> "Clang-tidy is enabled")
    else()
        message(SEND_ERROR "Clang-tidy requested but executable not found")
    endif()
else()
    message(===> "Clang-tidy is NOT enabled")
endif()